const path = require('path');

module.exports = {
  prefix: 'rc-widget',
  brandConfig: {
    id: '2110',
    code: 'rainbow',
    name: 'Rainbow Office',
    shortName: 'Rainbow Office',
    appName: 'Rainbow Office Embeddable',
    fullName: 'Rainbow Office',
    defaultLocale: 'fr-FR',
    supportedLocales: [
      'fr-FR',
      'en-US',
      'en-GB',
      'en-AU',
      'fr-CA',
      'de-DE',
      'it-IT',
      'es-ES',
      'es-419',
      'ja-JP',
      'pt-PT',
      'pt-BR',
      'zh-CN',
      'zh-TW',
      'zh-HK',
      'nl-NL',
      'ko-KR',
    ],
    eulaLink: 'https://www.ringcentral.fr/legal/privacy-notice.html',
    callWithJupiter: {
      link: 'https://app.rainbowoffice.com/',
      protocol: 'com.rainbowoffice.app://',
      name: 'Rainbow Office App',
    },
    callWithSoftphone: {
      protocol: 'rcmobile://',
      name: 'Rainbow Office Phone',
    },
    isDisableSpartan: true,
    allowRegionSettings: true,
    allowJupiterUniversalLink: false,
    rcvTeleconference: 'https://video.rainbowoffice.com/teleconference',
    rcvProductName: 'Rainbow Office Video',
    rcvMeetingTopic: "{extensionName}'s {brandName} Video meeting",
    rcvSettingsTitle: '{brandName} Video meeting settings',
    rcvInviteMeetingContent:
      "{accountName} vous a invité à une réunion {rcvProductName}.\n\nVeuillez rejoindre la réunion à l’aide de ce lien :\n    {joinUri}{passwordTpl}",
    assets: {
      logo: '/assets/rainbow/logo.svg',
      icon: '/assets/rainbow/icon.png',
    },
    showFeedback: false,
    enableEDP: true,
  },
  brandFolder: __dirname,
  assetsFolder: path.resolve(__dirname, '../../src/assets/rainbow'),
};
