const path = require('path');

module.exports = {
  prefix: 'rc-widget',
  brandConfig: {
    id: '6010',
    code: 'avaya',
    name: 'Avaya Cloud Office',
    shortName: 'Avaya Cloud Office',
    appName: 'Avaya Cloud Office Embeddable',
    fullName: 'Avaya Cloud Office',
    defaultLocale: 'en-US',
    supportedLocales: [
      'en-US',
      'en-GB',
      'en-AU',
      'fr-FR',
      'fr-CA',
      'de-DE',
      'it-IT',
      'es-ES',
      'es-419',
      'ja-JP',
      'pt-PT',
      'pt-BR',
      'zh-CN',
      'zh-TW',
      'zh-HK',
      'nl-NL',
      'ko-KR',
    ],
    callWithJupiter: {
      link: 'https://app.cloudoffice.avaya.com/',
      protocol: 'rcapp://',
      name: 'Avaya Cloud App',
    },
    callWithSoftphone: {
      protocol: 'rcmobile://',
      name: 'Avaya Cloud Office Phone',
    },
    isDisableSpartan: true,
    allowJupiterUniversalLink: true,
    allowRegionSettings: true,
    signupUrl: 'https://www.avaya.com/en/products/ucaas/cloud-office-pricing/',
    rcvTeleconference: 'https://video.cloudoffice.avaya.com/teleconference',
    rcvProductName: 'Avaya Cloud Office Video',
    rcvMeetingTopic: "{extensionName}'s {brandName} Video meeting",
    rcvSettingsTitle: '{brandName} Video meeting settings',
    rcvInviteMeetingContent:
      '{accountName} has invited you to a {rcvProductName} meeting.\n\nPlease join using this link:\n    {joinUri}{passwordTpl}',
    teleconference: 'https://meetings.ringcentral.com/teleconference',
    assets: {
      logo: '/assets/avaya/logo.svg',
      icon: '/assets/avaya/icon.svg',
    },
    showFeedback: false,
    enableEDP: true,
  },
  brandFolder: __dirname,
  assetsFolder: path.resolve(__dirname, '../../src/assets/avaya'),
};
